version: "3.8"
services:
  pharmacy-recommendation-redis:
    container_name: pharmacy-recommendation-redis
    build:
      # build 할 dockerfile과 경로 설정
      dockerfile: Dockerfile
      context: ./redis
    # repo/container 이름
    image: shh0429/pharmacy-recommendation-redis
    # port forwarding host:container
    ports:
      - "6379:6379"

  pharmacy-recommendation-database:
    container_name: pharmacy-recommendation-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: shh0429/pharmacy-recommendation-database
    environment:
      - MARIADB_DATABASE=pharmacy-recommendation
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    # 로컬의 경로 : 도커의 디렉토리   -> 로컬 경로의 정보를 토대로 도커 디렉토리에 만듬
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

# docker-compose 실행
# docker-compose -f docker-compose-local.yml up

# 서버가 잘 떴는지 확인하기
# docker ps