spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common
# 다른 환경마다 공통으로 사용할 정보를 만든다.
kakao:
  rest:
    api:
      key:${KAKAO_REST_API_KEY}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # 이렇게 하면 host:3306 > docker 3306으로 간다
    url: jdbc:mariadb://localhost:3306/pharmacy-recommendation
    # docker 는 .env 를 참조할 거고,   local에서 할 때는 환경변수를 추가@!
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # redis 설정하기
  redis:
    host: localhost
    port: 6379

  #jpa 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

pharmacy:
  recommendation:
    base:
      url: http://localhost:8080/dir/

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://pharmacy-recommendation-database:3306/pharmacy-recommendation
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: pharmacy-recommendation-redis
    port: 6379
  jpa:
    hibernate:
      ddl-auto: validate # prod 배포시 validate
    show-sql: true

pharmacy:
  recommendation:
    base:
      url: http://15.165.129.222/dir/ # aws ec2 ip 할당 받은 후 변경 예정